### PR TITLE
Tune PR approval using labels

### PR DESCRIPTION
**Pull request by ab77**
* https://github.com/balena-os/renovate-config/pull/18
* https://github.com/balena-io/renovate-config/pull/330

### CODE REVIEW

**Comment by klutchell** [comment]
squash and lgtm

**Comment by ab77** [comment]
> should we add these labels to the other renovate configs before merging this?

Yeah, the other two PRs are linked now.

> what about existing PRs, do the labels get added on the next renovate run?

PRs get updated on each renovate run, so we should start seeing the change in behaviour over the next hour or so..

**Comment by klutchell** [comment]
> > should we add these labels to the other renovate configs before merging this?
> 
> Yeah, the other two PRs are linked now.
> 
> > what about existing PRs, do the labels get added on the next renovate run?
> 
> PRs get updated on each renovate run, so we should start seeing the change in behaviour over the next hour or so..

In that case let's merge this tomorrow once we've seen the updated renovate PRs.

**Comment by klutchell** [comment]
It doesn't appear that labels have been updated on existing PRs?
https://github.com/balena-os/meta-balena/pull/2976

**Comment by klutchell** [comment]
lgtm

**Pull request merged**
